### ISSUE TITLE
PyCheesecake.org Down

### ISSUE THREAD

**Issue by eflee** [griggheo/cheesecake#10]
So, I realize that this isn't specifically about he code base - but I wanted to ensure it's tracked somewhere given that it's the home of the project's documentation.

As of 2/4/15 at 6:02pm, pycheesecake.org appears to be down. It returns a  GoDaddy parking page.

Is there an alternative location for documentation?

**Comment by griggheo** [comment]
Thanks @eflee. I don't maintain pycheesecake.org anymore. All the necessary information for running cheesecake is on GitHub now. See the README for documentation.
