### ISSUE TITLE
Update published version & site

### ISSUE THREAD

**Issue by glvnst** [griggheo/cheesecake#2]
The merged fix from issue #1 does not appear on [pypi][] nor on [the site][]; so currently many people won't benefit from that fix. Would you consider bumping the version number and updating pypi & the site?

Also, much less importantly, the site says "Cheesecake is under very active development," which seems like it may no longer be the case.

Finally, thank you very much for making pycheesecake! I'm finding it very helpful! If I can be of any assistance making these updates, please let me know.

[pypi]: https://pypi.python.org/pypi/Cheesecake
[the site]: http://www.pycheesecake.org/

**Comment by mkwiatkowski** [comment]
I've just uploaded a new release to PyPI: https://pypi.python.org/pypi/Cheesecake/0.6.2
